// <auto-generated />
namespace HTTP5212_HospitalProject_Team1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class pend : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pend));
        
        string IMigrationMetadata.Id
        {
            get { return "202207252134572_pend"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
