// <auto-generated />
namespace HTTP5212_HospitalProject_Team1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class shiftemployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shiftemployee));
        
        string IMigrationMetadata.Id
        {
            get { return "202207232022174_shift-employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
