// <auto-generated />
namespace HTTP5212_HospitalProject_Team1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class appointment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appointment));
        
        string IMigrationMetadata.Id
        {
            get { return "202207201748052_appointment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
